### ISSUE TITLE
Error when reading a real file when mocking a file in the same directory

### ISSUE THREAD

**Issue by Thomasdezeeuw** [tschaub/mock-fs#12]
Consider the following

test.js
```js
var mock = require('mock-fs');

mock({
  'index.js': 'module.exports = require("./sayHi");'
});

// Say hi
require('./index');
```

sayHi.js
```js
console.log('Hi');
```

Running ```node test``` results in the following error.

```
module.js:340
    throw err;
          ^
Error: Cannot find module './sayHi'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/thomas/dev/test/index.js:1:80)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by jviotti** [comment]
This behaviour is also giving trouble when using in conjunction with nock, as I get the error described in https://github.com/iojs/readable-stream/issues/119.

This is because `readable-stream` requires a file at runtime, and mock-fs gets in the way.

I think `mock-fs` should allow `require` to still work with real files as expected. There are other modules dedicated to mocking `require`.

**Comment by capaj** [comment]
@jviotti :+1:

**Comment by jtemplet** [comment]
I had the same problem and moving the require('./_stream_duplex') to the top of the file worked.

Any updates on this issue?

**Comment by JustBlackBird** [comment]
:+1: Faced the same problem when dealing with packages, that use `require` at runtime (`gulp-util` with its `log` feature).

**Comment by JustBlackBird** [comment]
Is there any way to mix real fs with mocked one?

**Comment by tschaub** [comment]
In `mock-fs@3.11.0` calls to `require()` use the real filesystem.  The old behavior was buggy - a mock file could only be `require`d if there was a file in the real filesystem at the same path.  See https://github.com/tschaub/mock-fs/issues/130#issuecomment-231533614 for a bit more detail.

**Comment by reddynr** [comment]
I am getting below error. Please advice. much appreciated . Thanks

Error: Cannot find module './internal/streams/BufferList'

 nodemon server.js

module.js:327
    throw err;
    ^

Error: Cannot find module './internal/streams/BufferList'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\reddynr\WebstormProjects\Client\node_modules\nodemon\node_modules\update-notifier\node_modules\latest-version\node_modules\package-json\node_module
s\got\node_modules\read-all-stream\node_modules\readable-stream\lib\_stream_readable.js:54:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
