### ISSUE TITLE
Can't require mock-fs in the Node REPL

### ISSUE THREAD

**Issue by rpaterson** [tschaub/mock-fs#15]
```shell
$ node
> var MockFS = require('mock-fs');
TypeError: Object #<Object> has no method '__get__'
    at Object.<anonymous> (/home/rpaterson/Programming/signpost/core/node_modules/mock-fs/lib/index.js:29:30)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at repl:1:14
    at REPLServer.self.eval (repl.js:110:21)
    at repl.js:249:20

$ node --version
v0.10.30
```

**Comment by meelispr** [comment]
Encountered same issue:
```
> var MockFS = require('mock-fs');
TypeError: undefined is not a function
    at Object.<anonymous> (<PROJECT ROOT>/node_modules/mock-fs/lib/index.js:41:30)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at repl:1:14
    at REPLServer.defaultEval (repl.js:132:27)
    at bound (domain.js:254:14)
$ node --version
v0.12.1
```
mock-fs version 2.6.0

**Comment by tschaub** [comment]
Requiring from the REPL is working for me (at `mock-fs@3.10.0` and Node 6.2).  Please reopen if you are still seeing this issue.
