### ISSUE TITLE
Add Support for Node js version 7.1.0

### ISSUE THREAD

**Issue by FJunior225** [tschaub/mock-fs#186]
When I run tests `npm run test`, I get this error:

```
$ npm run test

> Atlas-electron@2.0.20 test /Users/fcollins/Development/Atlas-orig/Atlas
> cross-env NODE_ENV=test babel-node node_modules/.bin/babel-istanbul cover --report cobertura --report html ./node_modules/.bin/_mocha --require ./server/test/setup.js ./src/**/*.test.js


/Users/fcollins/Development/Atlas-orig/Atlas/node_modules/mock-fs/lib/index.js:37
  throw new Error('Unsupported Node version: ' + nodeVersion);
        ^
Error: Unsupported Node version: 7.1.0
    at Object.<anonymous> (/Users/fcollins/Development/Atlas-orig/Atlas/node_modules/mock-fs/lib/index.js:37:9)
    at Module._compile (module.js:573:32)
    at Module._extensions..js (module.js:582:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/fcollins/Development/Atlas-orig/Atlas/node_modules/babel-register/lib/node.js:152:7)
    at Object.Module._extensions.(anonymous function) [as .js] (/Users/fcollins/Development/Atlas-orig/Atlas/node_modules/babel-istanbul/lib/hook.js:109:37)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/fcollins/Development/Atlas-orig/Atlas/src/atlas-api/project-logs/__tests__/project-log-files.test.js:9:1497)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions.(anonymous function) [as .js] (/Users/fcollins/Development/Atlas-orig/Atlas/node_modules/babel-istanbul/lib/hook.js:107:24)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at /Users/fcollins/Development/Atlas-orig/Atlas/node_modules/mocha/lib/mocha.js:222:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/fcollins/Development/Atlas-orig/Atlas/node_modules/mocha/lib/mocha.js:219:14)
    at Mocha.run (/Users/fcollins/Development/Atlas-orig/Atlas/node_modules/mocha/lib/mocha.js:487:10)
    at Object.<anonymous> (/Users/fcollins/Development/Atlas-orig/Atlas/node_modules/mocha/bin/_mocha:458:18)
    at Module._compile (module.js:573:32)
    at Module._extensions..js (module.js:582:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/fcollins/Development/Atlas-orig/Atlas/node_modules/babel-register/lib/node.js:152:7)
    at Object.Module._extensions.(anonymous function) [as .js] (/Users/fcollins/Development/Atlas-orig/Atlas/node_modules/babel-istanbul/lib/hook.js:109:37)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Function.Module.runMain (module.js:607:10)
    at runFn (/Users/fcollins/Development/Atlas-orig/Atlas/node_modules/babel-istanbul/lib/command/common/run-with-cover.js:125:16)
    at /Users/fcollins/Development/Atlas-orig/Atlas/node_modules/babel-istanbul/lib/command/common/run-with-cover.js:258:17
    at /Users/fcollins/Development/Atlas-orig/Atlas/node_modules/babel-istanbul/lib/util/file-matcher.js:68:16
    at /Users/fcollins/Development/Atlas-orig/Atlas/node_modules/babel-istanbul/node_modules/async/lib/async.js:52:16
    at /Users/fcollins/Development/Atlas-orig/Atlas/node_modules/babel-istanbul/node_modules/async/lib/async.js:361:13
    at /Users/fcollins/Development/Atlas-orig/Atlas/node_modules/babel-istanbul/node_modules/async/lib/async.js:52:16
    at done (/Users/fcollins/Development/Atlas-orig/Atlas/node_modules/babel-istanbul/node_modules/async/lib/async.js:246:17)
    at /Users/fcollins/Development/Atlas-orig/Atlas/node_modules/babel-istanbul/node_modules/async/lib/async.js:44:16
    at /Users/fcollins/Development/Atlas-orig/Atlas/node_modules/babel-istanbul/node_modules/async/lib/async.js:358:17
    at LOOP (fs.js:1611:14)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

**Comment by e-cloud** [comment]
now is v7.2.0

**Comment by e-cloud** [comment]
it's support now, this should be solved.

**Comment by tschaub** [comment]
Please reopen if you are still having trouble with Node 7 when using `mock-fs@3.12`.
