### ISSUE TITLE
Root Director already exists on Windows

### ISSUE THREAD

**Issue by dsbert** [tschaub/mock-fs#225]
The following is failing on Windows.

```
    mockfs.restore();
    mockfs(
      {
        "C:\\": {
          "temp.DAT": "original file contents",
          "upload.DAT": "new file contents"
        }
      },
      { createCwd: false }
    );
```

Results in this error

```
Item with the same name already exists: \\?\c:

      at Directory.Object.<anonymous>.Directory.addItem (node_modules/mock-fs/lib/directory.js:37:11)
      at populate (node_modules/mock-fs/lib/filesystem.js:160:15)
      at Function.Object.<anonymous>.FileSystem.create (node_modules/mock-fs/lib/filesystem.js:192:5)
      at mock (node_modules/mock-fs/lib/index.js:59:27)
      at Object.test.only (src/handlers/uploadHandler.test.js:131:5)
          at new Promise (<anonymous>)
```

Also, if I try changing it to this

```
    const tempPath = `C:\\temp.DAT`;
    const uploadPath = `C:\\upload.DAT`;

    mockfs.restore();
    mockfs({
      [tempPath]: "original file contents",
      [uploadPath]: "new file contents"
    });

    const copyFileAsync = util.promisify(fs.copyFile);
    await copyFileAsync(tempPath, uploadPath);
```

I end up with the following error;

```
[Error: ENOENT: no such file or directory, copyfile 'C:\temp.DAT' -> 'C:\upload.DAT']
```

**Comment by guilsa** [comment]
I'm having the same issue. A bit confused (probably my lack of understanding something).
