### ISSUE TITLE
Problem using jest: no such file or directory reporters/get_result_header.js

### ISSUE THREAD

**Issue by kristianmandrup** [tschaub/mock-fs#233]
```ts
import * as mockFs from 'mock-fs'

describe('collectTemplateFilesFrom', () => {
  const fileStruct = {
    'my': {
      'templates': {
        'a': `a`,
        'b': `b`
      }
    }
  }

  beforeEach(() => {
    // use mockfs
    mockFs(fileStruct)
  })

  it('mocks', () => {
    expect(1).toBe(1)
  })
})
```

with the following `jest` config:

```json
  "jest": {
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "json"
    ],
    "transform": {
      "\\.(ts|tsx)$": "<rootDir>/node_modules/ts-jest/preprocessor.js"
    },
    "testRegex": "/__tests__/.*\\.(ts|tsx|js)$"
  },
```

Produces:

```bash
$ jest __tests__/mock-fs/mock-fs.test.ts 
Error: ENOENT, no such file or directory '/usr/local/lib/node_modules/jest-cli/build/reporters/get_result_header.js'
    at Binding.<anonymous> (/Users/kristianmandrup/repos/project-maker/package-retriever/node_modules/mock-fs/lib/binding.js:1060:13)
    at maybeCallback (/Users/kristianmandrup/repos/project-maker/package-retriever/node_modules/mock-fs/lib/binding.js:42:17)
    at Binding.Object.<anonymous>.Binding.lstat (/Users/kristianmandrup/repos/project-maker/package-retriever/node_modules/mock-fs/lib/binding.js:1057:10)
    at Object.realpathSync (fs.js:1684:15)
    at toRealPath (module.js:171:13)
    at tryFile (module.js:167:22)
    at tryExtensions (module.js:179:22)
    at Function.Module._findPath (module.js:232:20)
    at Function.Module._resolveFilename (module.js:553:25)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at _load_get_result_header (/usr/local/lib/node_modules/jest-cli/build/reporters/default_reporter.js:22:88)
    at VerboseReporter.printTestFileHeader (/usr/local/lib/node_modules/jest-cli/build/reporters/default_reporter.js:186:41)
    at VerboseReporter.onTestResult (/usr/local/lib/node_modules/jest-cli/build/reporters/verbose_reporter.js:63:12)
    at /usr/local/lib/node_modules/jest-cli/build/reporter_dispatcher.js:45:24
    at Generator.next (<anonymous>)
    at step (/usr/local/lib/node_modules/jest-cli/build/reporter_dispatcher.js:1:322)
    at /usr/local/lib/node_modules/jest-cli/build/reporter_dispatcher.js:1:552
    at new Promise (<anonymous>)
    at /usr/local/lib/node_modules/jest-cli/build/reporter_dispatcher.js:1:233
    at ReporterDispatcher.onTestResult (/usr/local/lib/node_modules/jest-cli/build/reporter_dispatcher.js:46:10)
    at /usr/local/lib/node_modules/jest-cli/build/test_scheduler.js:116:35
    at Generator.next (<anonymous>)
    at step (/usr/local/lib/node_modules/jest-cli/build/test_scheduler.js:29:405)
    at /usr/local/lib/node_modules/jest-cli/build/test_scheduler.js:29:635
    at new Promise (<anonymous>)
    at /usr/local/lib/node_modules/jest-cli/build/test_scheduler.js:29:316
    at onFailure (/usr/local/lib/node_modules/jest-cli/build/test_scheduler.js:117:62)
    at /usr/local/lib/node_modules/jest-cli/node_modules/jest-runner/build/index.js:79:44
    at <anonymous>
```

If I comment out the `mockFs(fileStruct)` I don't get the error. Not sure if it conflicts with `jest` auto mocking? But this "feature" should now be turned off by default in `jest`

I get the same error even when using `mockFs({})`

**Comment by kristianmandrup** [comment]
Turns out that it was due to a missing `restore`. The fix is simply to restore the file system so that the Jest test reporter can work. 

```
  afterAll(() => {
    mockFs.restore()
  })
```
