### ISSUE TITLE
Ignore paths in node_modules

### ISSUE THREAD

**Issue by Xesenix** [tschaub/mock-fs#239]
Im trying to test if webpack builds with provided configuration but test fail on some libraries lazy requiring json configuration like for example:
```
Cannot find module './refs/json-schema-draft-06.json' from 'ajv.js'
```
Either give a way to disable mocking `require` or disable mocking paths by some reqexp.

**Comment by Xesenix** [comment]
Also, it may be that case that some coverage reports are broken because I see mock receives requests for map files and returns null for them...

**Comment by JeffSpies** [comment]
Just ran into the exact same error; ajv requires a json file in a function call, leading to this issue.

Any mock-fs friendly way to deal with this other than the very manual method suggested by the OP? :)

Thanks!

**Comment by DominicTobias** [comment]
Same issue I think, function I'm testing calls @babel/traverse and results in:

```
Error: ENOENT, no such file or directory '/Users/infensus/Sites/yebu/yebu-cli/node_modules/lodash/clone.js'
      at Binding.<anonymous> (node_modules/mock-fs/lib/binding.js:1166:13)
      at maybeCallback (node_modules/mock-fs/lib/binding.js:61:17)
      at Binding.lstat (node_modules/mock-fs/lib/binding.js:1163:10)
      at Object.realpathSync (fs.js:1478:29)
      at toRealPath (internal/modules/cjs/loader.js:205:13)
      at tryFile (internal/modules/cjs/loader.js:201:22)
      at tryExtensions (internal/modules/cjs/loader.js:213:22)
      at Function.Module._findPath (internal/modules/cjs/loader.js:295:20)
      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:600:25)
      at Function.Module._load (internal/modules/cjs/loader.js:529:25)
      at Module.require (internal/modules/cjs/loader.js:659:17)
      at require (internal/modules/cjs/helpers.js:22:18)
      at _clone (node_modules/@babel/traverse/lib/visitors.js:23:39)
      at Object.explode (node_modules/@babel/traverse/lib/visitors.js:102:30)
      at traverse (node_modules/@babel/traverse/lib/index.js:75:12)
      at NodePath.traverse (node_modules/@babel/traverse/lib/path/index.js:161:24)
      at Scope.crawl (node_modules/@babel/traverse/lib/scope/index.js:684:10)
      at Scope.init (node_modules/@babel/traverse/lib/scope/index.js:634:32)
      at NodePath.setScope (node_modules/@babel/traverse/lib/path/context.js:126:30)
      at NodePath.setContext (node_modules/@babel/traverse/lib/path/context.js:141:8)
      at NodePath.pushContext (node_modules/@babel/traverse/lib/path/context.js:207:8)
      at TraversalContext.visitQueue (node_modules/@babel/traverse/lib/context.js:106:14)
      at TraversalContext.visitSingle (node_modules/@babel/traverse/lib/context.js:90:19)
      at TraversalContext.visit (node_modules/@babel/traverse/lib/context.js:146:19)
      at Function.traverse.node (node_modules/@babel/traverse/lib/index.js:94:17)
      at traverse (node_modules/@babel/traverse/lib/index.js:76:12)
      at Promise (src/util/parser/annotate-js.js:71:5)
      at new Promise (<anonymous>)
      at annotate (src/util/parser/annotate-js.js:52:10)
      at process.internalTickCallback (internal/process/next_tick.js:77:7)
```

**Comment by mishelen** [comment]
Same issue with dynamic `require`
Kind of this doesn't help:

```js
mock({
 'node_modules/ajv/lib/refs/json-schema-draft-06.json': fs.readFileSync('node_modules/ajv/lib/refs/json-schema-draft-06.json'),
})
```

**Comment by mishelen** [comment]
^^ Solved with  https://github.com/tschaub/mock-fs/issues/213#issuecomment-418194809

**Comment by cshawaus** [comment]
Hi all,

Not sure if people are still trying to find a nice way of managing this or not but I came up with a cleaner solution compared to https://github.com/tschaub/mock-fs/issues/213#issuecomment-418194809.

My solution enforces lazy loading and skips non-essential directories using only `mock-fs` which brought my wait times for a single suite down from ~27 seconds on average to ~10 seconds which is still a little bit of time to wait but I haven't found another file system mocking solution that does the job better and has as good of an API as what mock-fs does.

```ts
import fs from 'fs'
import path from 'path'
import mockFS from 'mock-fs'

import type FileSystem from 'mock-fs/lib/filesystem'

function lazyLoadNodeModules(mockedFileSystem: FileSystem.DirectoryItems, from: string, depth = 6): void {
  const stat = fs.lstatSync(from)

  if (stat.isDirectory() && depth > 0) {
    for (const item of fs.readdirSync(from)) {
      if (item.startsWith('.') || item === '@types') {
        continue
      }

      lazyLoadNodeModules(mockedFileSystem, path.join(from, item), depth - 1)
    }
  } else if (stat.isFile()) {
    mockedFileSystem[from] = mockFS.load(from, { lazy: true })
  }
}

export default lazyLoadNodeModules
```

To use it, import the above code as a separate file in your test code and then run it with:

```ts
lazyLoadNodeModules(mockedFileSystem, path.resolve(path.join(process.cwd(), 'node_modules')))
```

By default this will:
1. Skip all dotfiles
2. Skip `@types` directories

I recommend only mocking what you need for smaller projects but mocking everything if like me you're doing webpack testing.

Hope this helps!
