### ISSUE TITLE
Innefective mark-compacts near heap limit Allocation failed

### ISSUE THREAD

**Issue by wyxos** [tschaub/mock-fs#266]
I've encountered an issue from the following scenario:

I have a test/code that is intended to write a file on a disk different from where the code runs (e.g. code runs on C: but attempts writing file at D:

When performing the above in Jest test, I encounter the following error after a long attempt trying to execute the test

```
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF6BBA3EEE5
 2: 00007FF6BBA18CD6
 3: 00007FF6BBA196E0
 4: 00007FF6BBE80D3E
 5: 00007FF6BBE80C6F
 6: 00007FF6BBDCC594
 7: 00007FF6BBDC2B67
 8: 00007FF6BBDC10DC
 9: 00007FF6BBDCA0B7
10: 00007FF6BBDCA136
11: 00007FF6BBEEF4C9
12: 00007FF6BBEF9EB0
13: 00007FF6BC019EC2
14: 0000033DAEE5C6C1
```

If I specify the drive when mocking, it throws an error.

- This doesn't work
```
mock({
        'D:/path/file.ext': original
      })
```

```
StatusCodeError: 404 - ""

      at new StatusCodeError (node_modules/request-promise-core/lib/errors.js:32:15)
      at node_modules/request-promise-core/lib/plumbing.js:97:41
```

This works
```
mock({
        'path/file.ext': original
      })
```

**Comment by wyxos** [comment]
I've dropped usage of mock-fs, closing the issue.
