### ISSUE TITLE
File descriptor issues with Mocha in ElementaryOS

### ISSUE THREAD

**Issue by josiah14** [tschaub/mock-fs#27]
It seems mock-fs can't create the mock filesystem correctly in ElementaryOS???  This code works fine on OSX.

The test:
```javascript
  /*
   * ::getFtpFileList
   */
  describe('::getFtpFileList', function () {
    var mockfs = require('mock-fs'),
        fs = require('fs');

    describe('When the directory contains only files', function () {
      before(function () {
        mockfs({
            'test': {
              'file.txt': 'contents',
              'file1.ext': ''
            }
        });
      });

      after(function () {
        mockfs.restore();
      });

      it('Injects a String Array of all the files with their full paths', function () {
        functions.getFtpFileList('test', function (err, files) {
          expect(files).to.deep.equal([
            'test/file.txt',
            'test/file1.ext'
          ]);

          expect(err).to.equal(null);
        });
      });
    });
```

The error
```
 6 passing (86ms)
  1 failing

  1) For module functions ::getFtpFileList When the directory contains only files "before all" hook:
     Uncaught Error: EBADF, bad file descriptor
    at Binding._getDescriptorById (/home/kyle/dstsystems-lateral/NodeOrchestrator/node_modules/mock-fs/lib/binding.js:189:11)
    at Binding.<anonymous> (/home/kyle/dstsystems-lateral/NodeOrchestrator/node_modules/mock-fs/lib/binding.js:375:27)
    at maybeCallback (/home/kyle/dstsystems-lateral/NodeOrchestrator/node_modules/mock-fs/lib/binding.js:27:18)
    at Binding.writeBuffer (/home/kyle/dstsystems-lateral/NodeOrchestrator/node_modules/mock-fs/lib/binding.js:374:10)
    at Object.fs.write (/home/kyle/dstsystems-lateral/NodeOrchestrator/node_modules/mock-fs/node/fs-0.10.28.js:513:11)
    at WriteStream._write (/home/kyle/dstsystems-lateral/NodeOrchestrator/node_modules/mock-fs/node/fs-0.10.28.js:1677:6)
    at doWrite (_stream_writable.js:226:10)
    at clearBuffer (_stream_writable.js:305:5)
    at onwrite (_stream_writable.js:263:7)
    at WritableState.onwrite (_stream_writable.js:97:5)
    at /home/kyle/dstsystems-lateral/NodeOrchestrator/node_modules/mock-fs/node/fs-0.10.28.js:1683:5
    at Object.wrapper [as oncomplete] (/home/kyle/dstsystems-lateral/NodeOrchestrator/node_modules/mock-fs/node/fs-0.10.28.js:510:5)
```

**Comment by Slayer95** [comment]
I am seeing this error at ``fs.write`` in one setup of Windows 7.
Also a similar ``EBADF`` error in a Windows 8 setup, though from ``fs.close``.

**Comment by MiniXC** [comment]
Also having this problem when using ``fs.readFileSync`` on Linux.
````
     Error: EBADF, bad file descriptor
      at Binding.<anonymous> (node_modules/mock-fs/lib/binding.js:343:13)
      at maybeCallback (node_modules/mock-fs/lib/binding.js:41:17)
      at Binding.read (node_modules/mock-fs/lib/binding.js:335:10)
      at Object.fs.readSync (node_modules/mock-fs/node/fs-6.0.0.js:651:19)
      at Object.fs.readFileSync (node_modules/mock-fs/node/fs-6.0.0.js:472:24)
````

**Comment by mrchief** [comment]
On Windows 7, I'm getting EBADF too. Just calling `mock()` throws this error. Also, `mock({'path/to/dir': {}})` throws same error.

**Comment by cco3** [comment]
What node versions are you all running?  I get this on 10, but not on 8.
