### ISSUE TITLE
MockFS hides errors when used with Mocha and CoffeeScript

### ISSUE THREAD

**Issue by lavelle** [tschaub/mock-fs#32]
I'm using MockFS in my test suite with Mocha and Chai, but when a test fails and an error is thrown, the following error message is shown regardless of what the actual error is:

```
ENOENT, no such file or directory '/path/to/file/throwing/error.js'
```

This error is only thrown when another error occurs in the code, so it's not a disaster, but without the actual error message to look at it's obviously incredibly difficult to debug what's going on and fix my tests.

Any ideas on what could be causing this, or any chance of a fix?

This looks like a very similar issue to #14

**Comment by tschaub** [comment]
@lavelle Can you provide some example code that demonstrates the issue?

**Comment by lavelle** [comment]
Okay this is super weird, I've been narrowing it down a bit more and it looks like it's caused by CoffeeScript.

When I run

```coffeescript
chai = require 'chai'
mockfs = require 'mock-fs'

fsContents =
  'foo.txt': 'bar'

mockfs(fsContents)
chai.should()

describe 'foo', ->
  it 'should bar', ->
    fs = require 'fs'
    fs.readFileSync('foo.txt', 'utf-8').should.equal('foo')
```

With `mocha --compilers coffee:coffee-script/register test.coffee` I get

```
  foo
    1) should bar


  0 passing (41ms)
  1 failing

  1) foo should bar:
     ENOENT, no such file or directory '/Users/giles/code/mockfstest2/test.coffee'
  Error: ENOENT, no such file or directory 'test.coffee'
```

But when I compile that to JS with `coffee -c test.coffee` to give

```js
// Generated by CoffeeScript 1.9.1
(function() {
  var chai, fsContents, mockfs;

  chai = require('chai');

  mockfs = require('mock-fs');

  fsContents = {
    'foo.txt': 'bar'
  };

  mockfs(fsContents);

  chai.should();

  describe('foo', function() {
    return it('should bar', function() {
      var fs;
      fs = require('fs');
      return fs.readFileSync('foo.txt', 'utf-8').should.equal('foo');
    });
  });

}).call(this);
```

and run `mocha test.js` I get

```
  foo
    1) should bar


  0 passing (14ms)
  1 failing

  1) foo should bar:

      AssertionError: expected 'bar' to equal 'foo'
      + expected - actual

      +"foo"
      -"bar"

      at Context.<anonymous> (test.js:21:57)
```

As expected. I know there's no guarantee of CoffeeScript support with this library, but anything that works for one *should* work with the other, and it would be interesting to find what's causing this and get it fixed.

Cheers.

**Comment by lavelle** [comment]
This isn't a big problem now I've worked this out, I can just compile the code to JS and then run the tests. Obviously if you can find a fix I'd be glad to have it though.

**Comment by tschaub** [comment]
I don't know how Mocha deals with compile-to-JS code, so I can't guess at what's going on.  I'm glad you got things working with JavaScript though.

**Comment by rohanorton** [comment]
Sorry for necroposting, but I had exactly the same issue with my mocha + coffeescript tests and found that a better solution than precompiling the coffeescript files to js was to wrap the calls to mock-fs in setup and teardown functions:

```coffee
mock = require('mock-fs')
fs = require('fs')
assert = require('assert')

beforeEach ->
    mock({
        foo: {
            bar: 'baz'
        }
    })

afterEach ->
    mock.restore()

describe 'mock-fs with mocha + coffeescript', ->
    it 'should work', ->
        expected = 'baz'
        actual = fs.readFileSync('foo/bar')
        assert.equal(actual, expected)
```
I hope that someone finds that useful

**Comment by bumpmann** [comment]
It looks like mock-fs is trying to read the stack and coffeescript uses fs when building the sourcemap for this trace:

(sorry for the verbose stacktrace but some places are useful)

```
Error: ENOENT, no such file or directory '/Users/bumpmann/Desktop/projects/oauthd/src/scaffolding/plugins/pluginsList.coffee'
    at Binding.<anonymous> (/Users/bumpmann/Desktop/projects/oauthd/node_modules/mock-fs/lib/binding.js:353:15)
    at maybeCallback (/Users/bumpmann/Desktop/projects/oauthd/node_modules/mock-fs/lib/binding.js:43:17)
    at Binding.open (/Users/bumpmann/Desktop/projects/oauthd/node_modules/mock-fs/lib/binding.js:327:10)
    at Object.fs.openSync (/Users/bumpmann/Desktop/projects/oauthd/node_modules/mock-fs/node/fs-7.0.0.js:604:18)
    at Object.fs.readFileSync (/Users/bumpmann/Desktop/projects/oauthd/node_modules/mock-fs/node/fs-7.0.0.js:472:33)
    at Object.readFileSync (/Users/bumpmann/Desktop/projects/oauthd/node_modules/mock-fs/lib/index.js:60:31)
    at Object.exports._compileFile (/Users/bumpmann/Desktop/projects/oauthd/node_modules/coffee-script/lib/coffee-script/coffee-script.js:257:14)
    at getSourceMap (/Users/bumpmann/Desktop/projects/oauthd/node_modules/coffee-script/lib/coffee-script/coffee-script.js:379:26)
    at getSourceMapping (/Users/bumpmann/Desktop/projects/oauthd/node_modules/coffee-script/lib/coffee-script/coffee-script.js:390:19)
    at formatSourcePosition (/Users/bumpmann/Desktop/projects/oauthd/node_modules/coffee-script/lib/coffee-script/coffee-script.js:338:16)
    at /Users/bumpmann/Desktop/projects/oauthd/node_modules/coffee-script/lib/coffee-script/coffee-script.js:408:33
    at Function.Error.prepareStackTrace (/Users/bumpmann/Desktop/projects/oauthd/node_modules/coffee-script/lib/coffee-script/coffee-script.js:411:7)
    at /Users/bumpmann/Desktop/projects/oauthd/node_modules/mock-fs/lib/index.js:56:32
    at go$readFile (/Users/bumpmann/Desktop/projects/oauthd/node_modules/graceful-fs/graceful-fs.js:73:14)
    at Object.readFile (/Users/bumpmann/Desktop/projects/oauthd/node_modules/graceful-fs/graceful-fs.js:70:12)
    at Object.readFile (/Users/bumpmann/Desktop/projects/oauthd/node_modules/jsonfile/index.js:29:6)
    at writeEntry (/Users/bumpmann/Desktop/projects/oauthd/src/scaffolding/plugins/pluginsList.coffee:20:10)
    at Object.updateEntry (/Users/bumpmann/Desktop/projects/oauthd/src/scaffolding/plugins/pluginsList.coffee:48:9)
    at /Users/bumpmann/Desktop/projects/oauthd/src/scaffolding/plugins/create.coffee:37:52
    at exec_callback (/Users/bumpmann/Desktop/projects/oauthd/tests/spec/scaffolding/plugins/index-spec.coffee:25:14)
    at /Users/bumpmann/Desktop/projects/oauthd/tests/spec/scaffolding/plugins/index-spec.coffee:36:30
    at /Users/bumpmann/Desktop/projects/oauthd/src/scaffolding/plugins/create.coffee:35:24
    at /Users/bumpmann/Desktop/projects/oauthd/node_modules/graceful-fs/graceful-fs.js:99:16
    at FSReqWrap.oncomplete (/Users/bumpmann/Desktop/projects/oauthd/node_modules/mock-fs/node/fs-7.0.0.js:87:15)
    at /Users/bumpmann/Desktop/projects/oauthd/node_modules/mock-fs/lib/binding.js:37:9
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

coffee-script@1.11.1
mock-fs@3.12.1

though i m not sure how to deal with it... sorry @rohanorton, your solution didn't work for me.

maybe @tschaub you can reopen or take a look at it ? Maybe by disabling the mocking when getting the stack with `new Error().stack` ?
