### ISSUE TITLE
Require error with io.js@2.2.x

### ISSUE THREAD

**Issue by blond** [tschaub/mock-fs#43]
In `io.js@2.2.0` were changes with `require` — https://github.com/nodejs/io.js/pull/1801

For real file system `require` works well, but with `mock-fs` fail with error.

**How to reproduce:**

```js
var path = require('path'),
    fs = require('fs'),
    mock = require('mock-fs');

mock({
    'file.js': 'module.exports = 10;'
});

var filename = path.resolve('file.js'),
    contents = fs.readFileSync(filename, 'utf-8');

// File exists
console.log(contents); // module.exports = 10;

var val = require(filename); // throw error

console.log(val);
```

**Expected:**

```
module.exports = 10;
10
```

**Actual:**

```
module.js:334
    throw err;
          ^
Error: Cannot find module '/Users/blond/projects/mock-test/file.js'
    at Function.Module._resolveFilename (module.js:332:15)
    at Function.Module._load (module.js:282:25)
    at Module.require (module.js:361:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/blond/projects/mock-test/index.js:14:11)
    at Module._compile (module.js:426:26)
    at Object.Module._extensions..js (module.js:444:10)
    at Module.load (module.js:351:32)
    at Function.Module._load (module.js:306:12)
    at Function.Module.runMain (module.js:467:10)

```

**Comment by programble** [comment]
Doesn't look like there would be any way to fix this in mock-fs :disappointed:

**Comment by blond** [comment]
May be need to mock `Module.require`?

**Comment by tschaub** [comment]
Please reopen if this is still an issue with the latest Node.  We may need to document it as a limitation.

**Comment by blond** [comment]
The same problem with `Node@4.x` and `Node@5.x`.

**Comment by rndD** [comment]
:+1: reproduced this error in `Node 4.x`.

**Comment by zxqfox** [comment]
@tschaub What do you think about mocking `require` (or something) in node 4.x+ via public API?
