### ISSUE TITLE
support for io.js v3.0.0

### ISSUE THREAD

**Issue by jfairley** [tschaub/mock-fs#54]
I'm seeing the following error when I try to run tests using io.js v3.0.0. I'm trying to upgrade from nodejs v0.10.38. Does `mock-fs` not support the latest io.js or is this error a red herring?

```
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^
Error: Unsupported Node version: 3.0.0
    at Object.<anonymous> (/Users/jfairley/Development/workspace-git/live-clipping/node_modules/mock-fs/lib/index.js:33:9)
    at Module._compile (module.js:430:26)
    at Object.Module._extensions..js (module.js:448:10)
    at Object.Module._extensions.(anonymous function) [as .js] (/Users/jfairley/Development/workspace-git/live-clipping/node_modules/gulp-istanbul/node_modules/istanbul/lib/hook.js:109:37)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module._load (/Users/jfairley/Development/workspace-git/live-clipping/node_modules/mock-require/index.js:13:27)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/jfairley/Development/workspace-git/live-clipping/app/service/clipBusinessService_test.js:35:12)
npm ERR! Test failed.  See above for more details.
```
```
 ⇒ nvm current
iojs-v3.0.0
```

**Comment by caitp** [comment]
This will be very handy. Temporarily disabling io.js builds on travis, but getting more coverage of the node ecosystem is important

**Comment by tschaub** [comment]
Support for `io.js@3.0` will take some work.  There are a number of non-trivial changes to address.  Patches requests welcome - I'll try to put some time into it post-grand-reconcilliation-merger-thing.

**Comment by JustBlackBird** [comment]
+1 for the issue :+1:
